# -*- coding: utf-8 -*-
"""Building Ude Points - ETL - Scrape Only - September 6 2025.ipynb

Automatically generated by Colab.
"""

# import packages
import argparse
import pandas as pd
import time

# import web scraping packages
from bs4 import BeautifulSoup

# colwidth limit none and other useful settings
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

"""# Preparation

# 1. Scrape the data

## 1.1 Load in dataset and filter out old dataless fights
"""

# Do not scrape fights from these events
to_be_excluded_hardcoded_list = ['UFC Live: Kongo vs Barry', 'UFC 127: Penn vs Fitch',
       'UFC 122: Marquardt vs Okami', 'UFC 120: Bisping vs Akiyama',
       'UFC Live: Vera vs Jones', 'UFC Fight Night: Maynard vs Diaz',
       'UFC 104: Machida vs Shogun', 'UFC Fight Night: Diaz vs Guillard',
       'UFC Fight Night: Condit vs Kampmann',
       'UFC 96: Jackson vs Jardine', 'UFC 95: Sanchez vs Stevenson',
       'UFC 93: Franklin vs Henderson', 'UFC 89: Bisping vs Leben',
       'UFC Fight Night: Diaz vs Neer', 'UFC 88: Breakthrough',
       'UFC 85: Bedlam', 'UFC 80: Rapid Fire',
       'UFC 75: Champion vs Champion', 'UFC 73: Stacked',
       'UFC 72: Victory', 'UFC 70: Nations Collide',
       'UFC 68: The Uprising', 'UFC Fight Night: Sanchez vs Riggs',
       'UFC 63: Hughes vs Penn', 'UFC 62: Liddell vs Sobral',
       'UFC 60: Hughes vs Gracie', 'UFC 55: Fury', 'UFC 45: Revolution',
       'UFC 43: Meltdown', 'UFC 41: Onslaught', 'UFC 35: Throwdown',
       'UFC 32: Showdown in the Meadowlands',
       'UFC 30: Battle on the Boardwalk', 'UFC 28: High Stakes',
       'UFC 27: Ultimate Bad Boyz', 'UFC 26: Ultimate Field Of Dreams',
       'UFC 24: First Defense', 'UFC 23: Ultimate Japan 2',
       'UFC 22: Only One Can be Champion',
       'UFC 21: Return of the Champions', 'UFC 20: Battle for the Gold',
       'UFC 19: Ultimate Young Guns',
       'UFC 18: The Road to the Heavyweight Title',
       'UFC - Ultimate Brazil', 'UFC 17: Redemption',
       'UFC 16: Battle in the Bayou', 'UFC - Ultimate Japan',
       'UFC 15: Collision Course', 'UFC 14: Showdown',
       'UFC 13: The Ultimate Force', 'UFC 12: Judgement Day',
       "UFC - Ultimate Ultimate '96", 'UFC 11: The Proving Ground',
       'UFC 10: The Tournament', 'UFC 9: Motor City Madness',
       'UFC 8: David vs Goliath', "UFC - Ultimate Ultimate '95",
       'UFC 7: The Brawl in Buffalo', 'UFC 6: Clash of the Titans',
       'UFC 5: The Return of the Beast', 'UFC 4: Revenge of the Warriors',
       'UFC 3: The American Dream', 'UFC 2: No Way Out']

def exclude_dataless_events(df: pd.DataFrame) -> pd.DataFrame:
    """Drops rows whose EVENT is in to_be_excluded_hardcoded_list (events too
    old to have detailed stats on UFCStats.com)."""
    return df[~df['EVENT'].isin(to_be_excluded_hardcoded_list)]

"""## 1.2 Start Scrape for Fight Data"""

# Create function that takes two dataframes -- fight_details and previous_complete -- and returns fight_details where 'URL' is not in previous_complete['fight_url'].
def filter_new_fights_set(latest_fights: pd.DataFrame, current_dataset: pd.DataFrame) -> pd.DataFrame:
    prev_urls = set(current_dataset['fight_url'])
    mask = ~latest_fights['URL'].isin(prev_urls)
    return latest_fights.loc[mask].reset_index(drop=True)


PLAYWRIGHT = None
BROWSER = None
PAGE = None

def start_browser():
    global PLAYWRIGHT
    global BROWSER
    global PAGE

    # Imported lazily, not at module load, so filter_new_fights_set/
    # exclude_dataless_events (pure logic, no browser needed) can be
    # imported and tested without playwright installed at all.
    from playwright.sync_api import sync_playwright

    PLAYWRIGHT = sync_playwright().start()

    BROWSER = PLAYWRIGHT.chromium.launch(
        headless=True
    )

    PAGE = BROWSER.new_page()

    # Block images/fonts/stylesheets
    PAGE.route(
        "**/*",
        lambda route: route.abort()
        if route.request.resource_type
        in ["image", "font", "stylesheet"]
        else route.continue_()
    )


def stop_browser():
    global PLAYWRIGHT
    global BROWSER

    if BROWSER:
        BROWSER.close()

    if PLAYWRIGHT:
        PLAYWRIGHT.stop()


# def fetch_page_content(url):
#     PAGE.goto(
#         url,
#         wait_until="domcontentloaded",
#         timeout=30000
#     )

#     html = PAGE.content()

#     return BeautifulSoup(
#         html,
#         "html.parser"
#     )

def fetch_page_content(url):

    for attempt in range(3):

        try:

            PAGE.goto(
                url,
                wait_until="domcontentloaded",
                timeout=30000
            )

            PAGE.wait_for_selector(
                "h2.b-content__title",
                timeout=10000
            )

            title = PAGE.title()

            if "Stats | UFC" not in title:
                raise Exception(
                    f"Unexpected title: {title}"
                )

            html = PAGE.content()

            return BeautifulSoup(
                html,
                "html.parser"
            )

        except Exception as e:

            if attempt == 2:
                raise

            print(
                f"Retrying {url} "
                f"(attempt {attempt + 2}/3)"
            )

            time.sleep(5)

# Mini-function to scrape the event title and URL
def scrape_event_details(soup):
    event_title_tag = soup.find('h2', class_='b-content__title').find('a')
    event_name = event_title_tag.text.strip() if event_title_tag else None
    event_url = event_title_tag['href'] if event_title_tag else None

    return event_name, event_url

# Mini-function to scrape fighter names and fight results
def scrape_fighters(soup):
    fighters = soup.find_all('a', class_='b-fight-details__person-link')
    name_fighter1 = fighters[0].text.strip()
    url_fighter1 = fighters[0]['href']
    name_fighter2 = fighters[1].text.strip()
    url_fighter2 = fighters[1]['href']

    results = soup.find_all('i', class_='b-fight-details__person-status')
    result_fighter1 = results[0].text.strip()
    result_fighter2 = results[1].text.strip()

    return name_fighter1, url_fighter1, result_fighter1, name_fighter2, url_fighter2, result_fighter2

# Mini-function to scrape fight details like weight class, method, time, etc.
def scrape_fight_details(soup):
    details_section = soup.find('div', class_='b-fight-details__fight')

    # Extract weight class from the fight title
    weight_class = details_section.find('i', class_='b-fight-details__fight-title').text.strip()

    # Initialize variables for method, round, time, time_format, finish_details, and details_summary
    method = None
    round_value = None
    time = None
    time_format = None
    finish_details = None

    # Extract fight content
    details = details_section.find_all('p', class_='b-fight-details__text')

    # Loop through each detail to find labels and their corresponding values
    for detail in details:
        items = detail.find_all('i', class_='b-fight-details__label')

        for label in items:
            label_text = label.text.strip()

            if label.find_next_sibling('i'):
                value = label.find_next_sibling('i').text.strip()
            else:
                value = label.parent.text.strip().replace(label_text, '').strip()

            if 'Method:' in label_text:
                method = value
            elif 'Round:' in label_text:
                round_value = value
            elif 'Time:' in label_text:
                time = value
            elif 'Time format:' in label_text:
                time_format = value
            elif 'Details:' in label_text:
                value = label.parent.parent.get_text(" ", strip=True).replace(label_text, "").strip()
                finish_details = value

    return weight_class, method, round_value, time, time_format, finish_details

# Mini-function to scrape the totals table
def scrape_totals(soup, url):
    tbodies = soup.find_all("tbody")

    for tbody in tbodies:
        rows = tbody.find_all("tr")

        if len(rows) == 0:
            continue

        cols = rows[0].find_all("td")

        if len(cols) == 10:
            totals = []
            for row in rows:
                row_cols = row.find_all("td")
                totals.append(
                    [
                        col.get_text("\n", strip=True)
                        for col in row_cols
                    ]
                )

            columns = [
                'Fighter', 'KD', 'Sig. str.', 'Sig. str. %', 'Total str.',
                'Td', 'Td %', 'Sub. att', 'Rev.', 'Ctrl'
            ]

            return pd.DataFrame(totals, columns=columns)

    print(f"No totals table found: {url}")
    return pd.DataFrame(
        columns=[
            'Fighter', 'KD', 'Sig. str.', 'Sig. str. %', 'Total str.',
            'Td', 'Td %', 'Sub. att', 'Rev.', 'Ctrl'
        ]
    )

# Mini-function to scrape the significant strikes table
def scrape_significant_strikes(soup, url):
    tbodies = soup.find_all("tbody")

    for tbody in tbodies:
        rows = tbody.find_all("tr")

        if len(rows) == 0:
            continue

        cols = rows[0].find_all("td")

        if len(cols) == 9:
            strikes = []
            for row in rows:
                row_cols = row.find_all("td")
                strikes.append(
                    [
                        col.get_text("\n", strip=True)
                        for col in row_cols
                    ]
                )

            columns = [
                'Fighter', 'Sig. str.', 'Sig. str. %', 'Head', 'Body',
                'Leg', 'Distance', 'Clinch', 'Ground'
            ]

            return pd.DataFrame(strikes, columns=columns)

    print(f"No significant strikes table found: {url}")
    return pd.DataFrame(
        columns=[
            'Fighter', 'Sig. str.', 'Sig. str. %', 'Head', 'Body',
            'Leg', 'Distance', 'Clinch', 'Ground'
        ]
    )


# Final function to combine everything into a pandas DataFrame
def scrape_ufc_fight(url):
    soup = fetch_page_content(url)
    if soup is None:
        return None

    # Scrape individual sections
    event_name, event_url = scrape_event_details(soup)
    name_fighter1, url_fighter1, result_fighter1, name_fighter2, url_fighter2, result_fighter2 = scrape_fighters(soup)
    weight_class, method, round_value, time, time_format, finish_details = scrape_fight_details(soup)

    # Pass the URL to the scraping functions
    totals_df = scrape_totals(soup, url)
    strikes_df = scrape_significant_strikes(soup, url)

    final_df = pd.concat([totals_df, strikes_df.drop(columns='Fighter', errors='ignore')], axis=1)

    # Add extra columns with fight metadata
    final_df['Event Name'] = event_name
    final_df['Event URL'] = event_url
    final_df['Weight Class'] = weight_class
    final_df['Method'] = method
    final_df['Round'] = round_value
    final_df['Time'] = time
    final_df['Time Format'] = time_format
    final_df['Finish Details'] = finish_details
    final_df['Fight URL'] = url

    final_df['Fighter 1 Name'] = name_fighter1
    final_df['Fighter 1 URL'] = url_fighter1
    final_df['Fighter 1 Result'] = result_fighter1
    final_df['Fighter 2 Name'] = name_fighter2
    final_df['Fighter 2 URL'] = url_fighter2
    final_df['Fighter 2 Result'] = result_fighter2

    return final_df

# Main function to put it all together
def scrape_fight_details_to_csv(
    df,
    current_dataset,
    col='URL',
    output_csv='scraped_fight_data.csv',
    batch_save=1000
):
    # Filter df
    df = filter_new_fights_set(df, current_dataset)

    all_fights_data = []  # List to hold all fights for final return
    batch_data = []       # List to hold current batch
    total_fights = len(df[col])
    failed_urls = []
    
    write_header = True   # Controls writing columns to CSV

    print(f"Starting to scrape {total_fights} fights...")
    start_browser()

    for index, url in enumerate(df[col]):
        try:
            fight_data = scrape_ufc_fight(url)

            if fight_data is not None:
                all_fights_data.append(fight_data)
                batch_data.append(fight_data)
            else:
                print(f"Failed to scrape: {url}")
                failed_urls.append({"url": url, "error": "Returned None"})

        except Exception as e:
            print("\n" + "=" * 80)
            print("SCRAPE FAILED")
            print(f"Fight #{index + 1}")
            print(url)
            print(type(e).__name__)
            print(str(e))
            print("=" * 80)

            failed_urls.append({"url": url, "error": str(e)})
            continue

        # Print an update every 1500 fights scraped
        if (index + 1) % 1500 == 0:
            print(f"Scraped {index + 1} out of {total_fights} fights.")

        # Save to CSV every batch_save fights using append mode
        if (index + 1) % batch_save == 0:
            if batch_data:
                batch_results = pd.concat(batch_data, ignore_index=True)
                
                batch_results.to_csv(
                    output_csv,
                    mode='a',
                    index=False,
                    header=write_header
                )
                
                write_header = False  # Turn off header after first write
                batch_data = []       # Clear batch
                
                print(f"Appended batch to {output_csv} after {index + 1} fights.")

                # Save failed URLs too
                if failed_urls:
                    pd.DataFrame(failed_urls).to_csv("failed_urls.csv", index=False)

    # Final save for any remaining fights in the last batch
    if batch_data:
        batch_results = pd.concat(batch_data, ignore_index=True)
        batch_results.to_csv(
            output_csv,
            mode='a',
            index=False,
            header=write_header
        )
        print(f"Appended final remaining fights to {output_csv}.")

    if failed_urls:
        pd.DataFrame(failed_urls).to_csv("failed_urls.csv", index=False)
        print(f"{len(failed_urls)} failed URLs saved to failed_urls.csv")

    stop_browser()

    # Return full dataframe if anything was scraped
    if all_fights_data:
        final_results = pd.concat(all_fights_data, ignore_index=True)
        print(f"Successfully finished scraping {len(final_results)} total rows.")
        return final_results
    else:
        print("No data scraped.")
        return pd.DataFrame()


def run_fight_scrape(fight_details_csv, current_dataset_csv, output_csv='scraped_latest_fights_df_final.csv',
                      batch_save=100):
    latest_fights = pd.read_csv(fight_details_csv)
    latest_fights = exclude_dataless_events(latest_fights)
    current_dataset = pd.read_csv(current_dataset_csv)

    latest_fights_data = scrape_fight_details_to_csv(latest_fights, current_dataset, batch_save=batch_save)

    # Drop rows where Fighter is null
    if not latest_fights_data.empty:
        latest_fights_data = latest_fights_data.dropna(subset=['Fighter']).reset_index(drop=True)
        latest_fights_data.to_csv(output_csv, index=False)
        print(f"Saved {len(latest_fights_data)} rows to {output_csv}")
    else:
        print("No new fights to scrape.")


def _parse_args():
    parser = argparse.ArgumentParser(description="Incremental UFCStats.com fight-detail scraper.")
    parser.add_argument("--fight-details-csv", required=True,
                         help="Path to ufc_fight_details.csv (source of ALL known fight URLs).")
    parser.add_argument("--current-dataset-csv", required=True,
                         help="Path to the current processed dataset, to skip already-scraped fights.")
    parser.add_argument("--output", default="scraped_latest_fights_df_final.csv")
    parser.add_argument("--batch-save", type=int, default=100)
    return parser.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    run_fight_scrape(
        fight_details_csv=args.fight_details_csv,
        current_dataset_csv=args.current_dataset_csv,
        output_csv=args.output,
        batch_save=args.batch_save,
    )


# ==============================================================================
# NEW EXECUTION BLOCK: Run specifically for any URLs found in failed_urls and export
# ==============================================================================

# missing_urls = [
#     "http://ufcstats.com/fight-details/a10deecfb8558335",
#     "http://ufcstats.com/fight-details/d5245f5b96b8afdf"
# ]

# print("Starting browser...")
# start_browser()

# recovered_fights = []

# for url in missing_urls:
#     print(f"Scraping {url}...")
#     try:
#         result = scrape_ufc_fight(url)
#         if result is not None:
#             recovered_fights.append(result)
#             print(f"Successfully scraped {url}")
#     except Exception as e:
#         print(f"Failed to scrape {url}: {e}")

# stop_browser()
# print("Browser stopped.")

# if recovered_fights:
#     # Combine the individual dataframes
#     final_recovered_df = pd.concat(recovered_fights, ignore_index=True)
    
#     # Drop rows where Fighter is null (matches the logic you had commented out)
#     final_recovered_df = final_recovered_df.dropna(subset=['Fighter']).reset_index(drop=True)
    
#     # Export to CSV
#     output_filename = "missing_fights_recovered.csv"
#     final_recovered_df.to_csv(output_filename, index=False)
#     print(f"Successfully saved {len(final_recovered_df)} rows to {output_filename}. You can now join this with your main dataset.")
# else:
#     print("No data was recovered.")